function matri=tom_perfmon_importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 22-Nov-2007 14:37:37

% Import the file
rawData1 = importdata(fileToRead1);

for i=2:size(rawData1,1)
    tmp=rawData1{i};
    rest=tmp;
    zz=1;
    for ii=1:10
        [a rest]=strtok(rest,'"');
        if isempty(strtrim(a))
            a='0';
        end
        if (ii==3)
            matri(i-1,zz)=str2num(a);
            zz=zz+1;
        end;
        if (ii==5)
            matri(i-1,zz)=str2num(a);
            zz=zz+1;
        end;
        if (ii==7)
            matri(i-1,zz)=str2num(a);
            zz=zz+1;
        end;
        
    end;
end;

