function success=tom_submit_to_hpcl_queue(settings)
hpcl = findResource('scheduler', 'type', 'generic:SGE');
hpcl.DataLocation = [settings.work_directory_path '/Hpcl_logdir'];
hpcl.SubmitFcn = @tom_hpcl_submitfcn;
hpcl.ParallelSubmitFcn = @tom_hpcl_submitfcn;
hpcl.ClusterMatlabRoot = '/raid5/apps/MATLAB/';
find3d_job=hpcl.createMatlabPoolJob('MaximumNumberOfWorkers',settings.nr_of_nodes,'MinimumNumberOfWorkers',settings.nr_of_nodes);
find3d_job.PathDependencies={...
    settings.work_directory_path; ...
    '/fs/pool/pool-bmsan-apps/tom_dev'; ...
    '/fs/pool/pool-bmsan-apps/tom_dev/Analysis'; ...
    '/fs/pool/pool-bmsan-apps/tom_dev/Classify'; ...
    '/fs/pool/pool-bmsan-apps/tom_dev/Display'; ...
    '/fs/pool/pool-bmsan-apps/tom_dev/Filtrans'; ...
    '/fs/pool/pool-bmsan-apps/tom_dev/Geom'; ...
    '/fs/pool/pool-bmsan-apps/tom_dev/IOfun'; ...
    '/fs/pool/pool-bmsan-apps/tom_dev/Misc'; ...
    '/fs/pool/pool-bmsan-apps/tom_dev/Parallel'; ...
    '/fs/pool/pool-bmsan-apps/tom_dev/Reconstruction'; ...
    '/fs/pool/pool-bmsan-apps/tom_dev/Spider'; ...
    '/fs/pool/pool-bmsan-apps/tom_dev/Sptrans'; ...
    '/fs/pool/pool-bmsan-apps/tom_dev/Util'; ...
    '/fs/pool/pool-bmsan-apps/tom_dev/av2'; ...
    '/fs/pool/pool-bmsan-apps/tom_dev/av3'; ...
    '/fs/pool/pool-bmsan-apps/tom_dev/xmipp'};
tom_job.createTask('call_script',1);
tom_job.submit;
OK=waitForState(tom_job,'queued',60);
if OK==1
    msg='tom job queued.';
    success=1;
else
    msg='tom job not queued.';
    success=0;
end;
if OK==1
    [n msg]=unix('qstat');
end