%%
function parallelJob = tom_os3_prepareParallel(managerName,managerType,distributionType,jobName)
%default values
%managerName = 'titan_jobmanager'
%managerType = 'jobmanager'
%jobType     = 'TaskParallel'

    jobSheduler = findResource('scheduler','type',managerType,'lookupurl', managerName);

    if(isempty(jobSheduler))
        error(['No jobSheduler found! Is ' managerName ' correct?']);
    end;
%%  choose type of parallelization    
    if(strcmp(distributionType,'TaskParallel'))
        parallelJob = createJob(jobSheduler,'Name',jobName);
    else
        parallelJob = createParallelJob(jobSheduler,'Name',jobName);
    end;
    
%%  set paths of functions    
    paths={ '/fs/pool/pool-bmsan-apps/tom_dev/IOfun' ...
            '/fs/pool/pool-bmsan-apps/tom_dev/Filtrans/'  ...
            '/fs/pool/pool-bmsan-apps/tom_dev/Analysis/' ...
            '/fs/pool/pool-bmsan-apps/tom_dev/Misc/' ...
            '/fs/pool/pool-bmsan-apps/tom_dev/Sptrans/' ...
            '/fs/pool/pool-bmsan-apps/tom_dev/Geom/' ...
            '/fs/pool/pool-bmsan-apps/tom_dev/Oscar3/matlabPicker/search'  ...
            '/fs/pool/pool-bmsan-apps/tom_dev/Oscar3/matlabPicker/analyze' ...
            '/fs/pool/pool-bmsan-apps/tom_dev/Oscar3/matlabPicker/overlap' ...
            '/fs/pool/pool-bmsan-apps/tom_dev/Oscar3/matlabPicker/tools' ...
            '/fs/pool/pool-bmsan-apps/tom_dev/Oscar3/matlabPicker/io' ...
            '/fs/pool/pool-bmsan-apps/tom_dev/Oscar3/matlabPicker/modifications' ...
            '/fs/pool/pool-bmsan-apps/tom_dev/Oscar3/matlabPicker/options' ... 
            '/fs/pool/pool-bmsan-apps/tom_dev/Oscar3/matlabPicker/fftw' ...
            '/fs/pool/pool-bmsan-apps/tom_dev/Oscar3/matlabPicker/results' ...
            '/fs/pool/pool-bmsan-apps/tom_dev/Oscar3/matlabPicker/classification' ...
            '/fs/pool/pool-bmsan-apps/tom_dev/Oscar3/matlabPicker/picker' ...
            '/fs/pool/pool-bmsan-apps/tom_dev/Oscar3/matlabPicker/statistics'};
    
    set(parallelJob,'PathDependencies',paths);
