function index=tom_av3_angle2index(angle, angle_start, angular_incr,angle_end)
%TOM_AV3_ANGLE2INDEX creates angle index from Euler angles
%
%   index=tom_av3_angle2index(angle, angle_start, angular_incr,angle_end)
%
%   index is assumed to be generated by loop, from inner to outer: phi, psi, theta,
%   lowest index is zero.
%
%PARAMETERS
%
%  INPUT
%   angle               ...
%   angle_start         [phi_start psi_start theta_start]      angle chosen as
%                        start value as vector 
%   angular_incr        [phi_increment psi_increment theta_increment] as
%                        vector
%   angle_end           [phi_end psi_end theta_end] phi psi and theta choosen as 
%                        start value as vector
%  
%  OUTPUT
%   index               index corresponding to angle
%
%EXAMPLE
%   index=tom_av3_angle2index([90 270 330], [0 0 0], [10 15 10 ],[300 330 360])
%
%REFERENCES
%
%SEE ALSO
%   molmatch.exe (MPI c-program), av3_index2angle, av3_index2angle_new
%
%   created by SN 12/14/05
%
%   Nickell et al., 'TOM software toolbox: acquisition and analysis for electron tomography',
%   Journal of Structural Biology, 149 (2005), 227-234.
%
%   Copyright (c) 2004-2007
%   TOM toolbox for Electron Tomography
%   Max-Planck-Institute of Biochemistry
%   Dept. Molecular Structural Biology
%   82152 Martinsried, Germany
%   http://www.biochem.mpg.de/tom


index=0;
for i=angle_start(3):angular_incr(3):angle_end(3)
    for j=angle_start(2):angular_incr(2):angle_end(2)
        for k=angle_start(1):angular_incr(1):angle_end(1)
            if i==angle(3) & j==angle(2) & k==angle(1);
                return;
            end;
            index=index+1;
        end;
    end;
end;
                


